{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prometheus-aggregator-gateway.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := .Values.ingress.host -}}
{{- $path := .Values.ingress.path -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "prometheus-aggregator-gateway.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ $host }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
        path: {{ $path }}
{{- end }}
