{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prometheus-aggregator-gateway.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $path := .Values.ingress.path -}}
{{- $ingressPath := .Values.ingress.path }}
{{- $needsRewrite := and ($ingressPath) (ne $ingressPath "/") }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
{{ include "prometheus-aggregator-gateway.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Release.Namespace }}-nginx
    {{- if $needsRewrite }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.bodySize | default "1m" }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- if $needsRewrite }}
          - path: {{ $ingressPath }}(/|$)(.*)
          {{- else }}
          - path: {{ $ingressPath }}
          {{- end }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: $svcPort
  {{- end }}
{{- end }}