replicaCount: 1

image:
  repository: "romiko/appinsights-prometheus-exporter"
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {} 

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
  host: rangerrom.com
  path: /

environmentFromSecret: prometheus-appinsights-exporter-secrets
environment:
  - name: LOG_LEVEL
    value: debug

secrets:
  appinsightsAppId: basek4encodedappid
  appinsightsKey: basek4encodedkey