{{- $appid := .Values.secrets.appinsightsAppId -}}
{{- $key:= .Values.secrets.appinsightsKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-appinsights-exporter-secrets
  namespace: default
data:
  AZURE_APP_INSIGHTS_APP_ID: {{$appid}}
  AZURE_APP_INSIGHTS_KEY: {{$key}}
type: Opaque