{{- range .Values.jobs }}
{{- $deploymentName := printf "%s-%s" $.Release.Name .name -}}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ $deploymentName }}-secret
  labels:
    app: {{ $deploymentName }}
    chart: {{ include "sc-cypress-cron-job.chart" $ }}
data:
{{- range $key, $val := .secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end}}
---
{{- end }}
