dependencies:
- name: nginx-ingress
  alias: nginx-ingress
  version: 1.41.3
  repository: "https://charts.helm.sh/stable"
  condition: nginx-ingress.enabled

- name: nginx-ingress
  alias: public-nginx-ingress
  version: 1.41.3
  repository: "https://charts.helm.sh/stable"
  condition: public-nginx-ingress.enabled
