image:
  repository: "weaveworks/prom-aggregation-gateway"
  tag: master-123c6bfc
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {} 

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  bodySize: ""
  path: /
  hosts:
    - rangerrom.com
  tls:
      - secretName: tls-secret
        hosts:
          - rangerrom.com
  annotations: {}

  affinity: {}
  nodeSelector: {}
